### ISSUE TITLE
auto_orient breaks with png files.

### ISSUE THREAD

**Issue by JavoByte** [CodeSleeve/stapler#100]
I was trying to use auto_orient feature but function exif_read_data() throws an Exception with png files and this exception is not handled. Should I check before if my file is png?? Or is there other way to auto_orient only jpg files??

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by fabianpimminger** [comment]
Any news on this issue?

**Comment by tabennett** [comment]
This is now fixed in 1.1.0.  I'm working on getting a release out for laravel-stapler. Until then, laravel-stapler master is set to user stapler 1.1.0 if you'd like to test this.

**Comment by ByUsKevin** [comment]
Thanks. But unfortunately, for me this problem is still not fixed. (even in 1.1.0 version). Only me?!!

**Comment by tabennett** [comment]
Just pushed a hot fix for this one. I forgot to load `ErrorException` into the current namespace, so it was never actually catching the errors. That's a facepalm.

**Comment by ByUsKevin** [comment]
It works perfectly now! Thanks Travis
